before:
  hooks:
    - go mod download

builds:
  - main: ./cmd/automount
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - 386
      - amd64
      - arm64
    flags:
      - -trimpath

archives:
  - name_template: '{{ .ProjectName }}_edge_{{ .Os }}_{{ .Arch }}'

release:
  disable: true

dockers:
  - image_templates:
      - 'docker.io/mvisonneau/automount:latest-amd64'
      - 'ghcr.io/mvisonneau/automount:latest-amd64'
    ids: [automount]
    goarch: amd64
    use_buildx: true
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/mvisonneau/automount
      - --label=org.opencontainers.image.source=https://github.com/mvisonneau/automount
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=Apache-2.0

  - image_templates:
      - 'docker.io/mvisonneau/automount:latest-arm64v8'
      - 'ghcr.io/mvisonneau/automount:latest-arm64v8'
    ids: [automount]
    goarch: arm64
    use_buildx: true
    build_flag_templates:
      - --platform=linux/arm64/v8
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/mvisonneau/automount
      - --label=org.opencontainers.image.source=https://github.com/mvisonneau/automount
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=Apache-2.0

docker_manifests:
  - name_template: docker.io/mvisonneau/automount:latest
    image_templates:
      - docker.io/mvisonneau/automount:latest-amd64
      - docker.io/mvisonneau/automount:latest-arm64v8

  - name_template: ghcr.io/mvisonneau/automount:latest
    image_templates:
      - ghcr.io/mvisonneau/automount:latest-amd64
      - ghcr.io/mvisonneau/automount:latest-arm64v8

signs:
  - artifacts: checksum
    args:
      [
        '-u',
        'C09CA9F71C5C988E65E3E5FCADEA38EDC46F25BE',
        '--output',
        '${signature}',
        '--detach-sign',
        '${artifact}',
      ]

checksum:
  name_template: '{{ .ProjectName }}_edge_sha512sums.txt'
  algorithm: sha512

changelog:
  skip: true
